### ISSUE TITLE
Make the video public and improve docs 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [benawad/vstodo#1]

**Comment by mdrakea** [comment]
agreed, this is a good idea to get more people on the project with easier contributing instructions and, publicize this project, as well.

**Comment by azinit** [comment]
#4 - yeap, why you hide video from public access, but not remove from docs? 😮

**Comment by mdrakea** [comment]
I mean, I've seen github repos go up a little early, but not *16 hours* early.
