### ISSUE TITLE
Hmmm ... [video is private]

### ISSUE THREAD

**Issue by azinit** [benawad/vstodo#4]
![image](https://user-images.githubusercontent.com/42924400/103205868-9a78ad80-490b-11eb-8e99-e8adb1cac8e2.png)

**Comment by azinit** [comment]
![image](https://user-images.githubusercontent.com/42924400/103205899-aebcaa80-490b-11eb-8f61-e17861d79557.png)

**Comment by fast-and-curious-1910** [comment]
He will  publish it probably. seems intresting.

**Comment by azinit** [comment]
Still actual =)

![image](https://user-images.githubusercontent.com/42924400/103706750-6a41a680-4fbe-11eb-8762-b8543c93c7ec.png)
